export interface FieldTypeInfo {
  label: string;
  icon: string;
  description: string;
  hasOptions: boolean;
  hasPlaceholder: boolean;
  hasDefaultValue: boolean;
  hasRequired: boolean;
  hasHelpText: boolean;
  hasMultiple: boolean;
  hasConditions: boolean;
}

export const fieldTypes: Record<string, FieldTypeInfo> = {
  // Backend enum types (uppercase)
  TEXT: {
    label: 'Text',
    icon: 'text',
    description: 'Short text like a name or title',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  LONG_TEXT: {
    label: 'Long Text',
    icon: 'paragraph',
    description: 'Multiple lines of text',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  EMAIL: {
    label: 'Email',
    icon: 'mail',
    description: 'Email address',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  PHONE: {
    label: 'Phone',
    icon: 'phone',
    description: 'Phone number',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  URL: {
    label: 'URL',
    icon: 'link',
    description: 'Website URL',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  NUMBER: {
    label: 'Number',
    icon: 'number',
    description: 'Numeric values only',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  DATE: {
    label: 'Date',
    icon: 'calendar',
    description: 'Date picker',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  TIME: {
    label: 'Time',
    icon: 'clock',
    description: 'Time picker',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  DATETIME: {
    label: 'Date & Time',
    icon: 'calendar-clock',
    description: 'Date and time picker',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  RATING: {
    label: 'Rating',
    icon: 'star',
    description: 'Star rating input',
    hasOptions: false,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  SLIDER: {
    label: 'Slider',
    icon: 'slider',
    description: 'Range slider input',
    hasOptions: false,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  SCALE: {
    label: 'Scale',
    icon: 'scale',
    description: 'Numeric scale (1-10)',
    hasOptions: false,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  DROPDOWN: {
    label: 'Dropdown',
    icon: 'dropdown',
    description: 'Dropdown select',
    hasOptions: true,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  CHECKBOX: {
    label: 'Checkbox',
    icon: 'checkbox',
    description: 'Multiple choice checkboxes',
    hasOptions: true,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: true,
    hasConditions: true,
  },
  RADIO: {
    label: 'Radio',
    icon: 'radio',
    description: 'Single choice radio buttons',
    hasOptions: true,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  FILE: {
    label: 'File Upload',
    icon: 'upload',
    description: 'File upload input',
    hasOptions: false,
    hasPlaceholder: false,
    hasDefaultValue: false,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: true,
    hasConditions: true,
  },
  
  // Legacy lowercase types for backwards compatibility
  text: {
    label: 'Text',
    icon: 'text',
    description: 'Short text like a name or title',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  long_text: {
    label: 'Long Text',
    icon: 'paragraph',
    description: 'Multiple lines of text',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  email: {
    label: 'Email',
    icon: 'mail',
    description: 'Email address',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  phone: {
    label: 'Phone',
    icon: 'phone',
    description: 'Phone number',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  url: {
    label: 'URL',
    icon: 'link',
    description: 'Website URL',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  number: {
    label: 'Number',
    icon: 'number',
    description: 'Numeric values only',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  date: {
    label: 'Date',
    icon: 'calendar',
    description: 'Date picker',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  time: {
    label: 'Time',
    icon: 'clock',
    description: 'Time picker',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  datetime: {
    label: 'Date & Time',
    icon: 'calendar-clock',
    description: 'Date and time picker',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  rating: {
    label: 'Rating',
    icon: 'star',
    description: 'Star rating input',
    hasOptions: false,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  slider: {
    label: 'Slider',
    icon: 'slider',
    description: 'Range slider input',
    hasOptions: false,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  scale: {
    label: 'Scale',
    icon: 'scale',
    description: 'Numeric scale (1-10)',
    hasOptions: false,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  dropdown: {
    label: 'Dropdown',
    icon: 'dropdown',
    description: 'Dropdown select',
    hasOptions: true,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  checkbox: {
    label: 'Checkbox',
    icon: 'checkbox',
    description: 'Multiple choice checkboxes',
    hasOptions: true,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: true,
    hasConditions: true,
  },
  radio: {
    label: 'Radio',
    icon: 'radio',
    description: 'Single choice radio buttons',
    hasOptions: true,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  file: {
    label: 'File Upload',
    icon: 'upload',
    description: 'File upload input',
    hasOptions: false,
    hasPlaceholder: false,
    hasDefaultValue: false,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: true,
    hasConditions: true,
  },
}; 