export interface FieldTypeInfo {
  label: string;
  icon: string;
  description: string;
  hasOptions: boolean;
  hasPlaceholder: boolean;
  hasDefaultValue: boolean;
  hasRequired: boolean;
  hasHelpText: boolean;
  hasMultiple: boolean;
  hasConditions: boolean;
}

export const fieldTypes: Record<string, FieldTypeInfo> = {
  text: {
    label: 'Text',
    icon: 'text',
    description: 'Short text like a name or title',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  textarea: {
    label: 'Paragraph',
    icon: 'paragraph',
    description: 'Multiple lines of text',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  number: {
    label: 'Number',
    icon: 'number',
    description: 'Numeric values only',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  email: {
    label: 'Email',
    icon: 'mail',
    description: 'Email address',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  phone: {
    label: 'Phone',
    icon: 'phone',
    description: 'Phone number',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  date: {
    label: 'Date',
    icon: 'calendar',
    description: 'Date picker',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  checkbox: {
    label: 'Checkbox',
    icon: 'checkbox',
    description: 'Single checkbox',
    hasOptions: false,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  checkboxes: {
    label: 'Checkboxes',
    icon: 'checkboxes',
    description: 'Multiple checkboxes',
    hasOptions: true,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: true,
    hasConditions: true,
  },
  radio: {
    label: 'Radio',
    icon: 'radio',
    description: 'Radio buttons',
    hasOptions: true,
    hasPlaceholder: false,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  select: {
    label: 'Dropdown',
    icon: 'dropdown',
    description: 'Dropdown select',
    hasOptions: true,
    hasPlaceholder: true,
    hasDefaultValue: true,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  heading: {
    label: 'Heading',
    icon: 'heading',
    description: 'Section heading',
    hasOptions: false,
    hasPlaceholder: false,
    hasDefaultValue: false,
    hasRequired: false,
    hasHelpText: true,
    hasMultiple: false,
    hasConditions: true,
  },
  divider: {
    label: 'Divider',
    icon: 'divider',
    description: 'Section divider',
    hasOptions: false,
    hasPlaceholder: false,
    hasDefaultValue: false,
    hasRequired: false,
    hasHelpText: false,
    hasMultiple: false,
    hasConditions: true,
  },
  file: {
    label: 'File Upload',
    icon: 'file',
    description: 'File upload field',
    hasOptions: false,
    hasPlaceholder: true,
    hasDefaultValue: false,
    hasRequired: true,
    hasHelpText: true,
    hasMultiple: true,
    hasConditions: true,
  },
}; 