name: Final Fix

on:
  workflow_dispatch:

jobs:
  final-fix:
    runs-on: ubuntu-latest
    
    steps:
    - name: Final Frontend Fix
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "=== Final Fix - Frontend Startup ==="
          
          # Source NVM
          export NVM_DIR="/home/ec2-user/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          
          APP_DIR="/home/ec2-user/formatic-unified"
          FRONTEND_DIR="$APP_DIR/frontend"
          
          echo "=== Stopping frontend PM2 process ==="
          pm2 delete frontend || echo "Frontend not running"
          
          cd $FRONTEND_DIR
          
          echo "=== Checking standalone server ==="
          if [ -f ".next/standalone/server.js" ]; then
            echo "✅ Standalone server found - using that"
            FRONTEND_START_CMD="node .next/standalone/server.js"
          else
            echo "⚠️  Standalone server not found - using Next.js directly"
            FRONTEND_START_CMD="node_modules/.bin/next start"
          fi
          
          echo "=== Starting frontend with correct command ==="
          cd $FRONTEND_DIR
          pm2 start "$FRONTEND_START_CMD" --name frontend --cwd "$FRONTEND_DIR"
          
          echo "=== Waiting for frontend to start ==="
          sleep 8
          
          echo "=== Testing frontend health ==="
          for i in {1..6}; do
            echo "Frontend test $i/6..."
            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000 || echo "000")
            echo "HTTP Response: $HTTP_CODE"
            
            if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "302" ]; then
              echo "✅ Frontend is responding!"
              break
            elif [ $i -eq 6 ]; then
              echo "❌ Frontend not responding after 6 attempts"
              echo "Checking PM2 logs..."
              pm2 logs frontend --lines 10
            else
              echo "⏳ Waiting 5 more seconds..."
              sleep 5
            fi
          done
          
          echo "=== Final PM2 Status ==="
          pm2 status
          pm2 save
          
          echo "=== Testing full application ==="
          echo "Backend API (should be 404 or 401):"
          curl -s -o /dev/null -w "HTTP %{http_code}\n" http://localhost:3001/api/auth/session
          
          echo "Frontend (should be 200):"
          curl -s -o /dev/null -w "HTTP %{http_code}\n" http://localhost:3000
          
          echo "=== Reloading Nginx ==="
          sudo systemctl reload nginx
          
          echo "=== Testing public domain ==="
          echo "Public frontend test:"
          curl -s -o /dev/null -w "HTTP %{http_code}\n" https://datizmo.com
          
          echo "Public API test:"
          curl -s -o /dev/null -w "HTTP %{http_code}\n" https://datizmo.com/api/auth/session
          
          echo "=== 🎉 FINAL FIX COMPLETED! ==="
          echo "Your application should now be fully functional at https://datizmo.com" 