name: Immediate Fix

on:
  workflow_dispatch:

jobs:
  immediate-fix:
    runs-on: ubuntu-latest
    
    steps:
    - name: Fix Backend Startup Path
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "=== Immediate Fix - Correcting Backend Path ==="
          
          # Source NVM
          export NVM_DIR="/home/ec2-user/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          
          APP_DIR="/home/ec2-user/formatic-unified"
          BACKEND_DIR="$APP_DIR/backend"
          
          echo "=== Stopping PM2 processes ==="
          pm2 delete all || echo "No processes to delete"
          
          echo "=== Checking backend dist structure ==="
          cd $BACKEND_DIR
          find dist/ -name "*.js" -type f | head -10
          
          echo "=== Finding the correct main.js path ==="
          MAIN_PATH=""
          if [ -f "dist/main.js" ]; then
            MAIN_PATH="$BACKEND_DIR/dist/main.js"
          elif [ -f "dist/src/main.js" ]; then
            MAIN_PATH="$BACKEND_DIR/dist/src/main.js"
          else
            echo "❌ Cannot find main.js in expected locations"
            exit 1
          fi
          
          echo "✅ Found main.js at: $MAIN_PATH"
          
          echo "=== Ensuring environment files ==="
          if [ ! -f "$BACKEND_DIR/.env" ]; then
            echo "❌ Backend .env missing"
            exit 1
          fi
          
          # Create frontend .env.production if missing
          if [ ! -f "$APP_DIR/frontend/.env.production" ]; then
            echo "Creating frontend .env.production"
            cat > "$APP_DIR/frontend/.env.production" << 'ENVEOF'
          NODE_ENV=production
          NEXT_PUBLIC_API_URL=https://datizmo.com/api
          NEXTAUTH_URL=https://datizmo.com
          NEXTAUTH_SECRET=your-secret-key-here
          ENVEOF
          fi
          
          echo "=== Running Prisma setup ==="
          cd $BACKEND_DIR
          npx prisma generate || echo "Prisma generate failed, continuing..."
          
          echo "=== Starting backend with correct path ==="
          pm2 start $MAIN_PATH --name backend --cwd $BACKEND_DIR
          
          echo "=== Waiting for backend to start ==="
          sleep 5
          
          echo "=== Testing backend ==="
          if curl -s http://localhost:3001/api/auth/session > /dev/null; then
            echo "✅ Backend is responding!"
          else
            echo "❌ Backend not responding yet, checking logs..."
            pm2 logs backend --lines 20
          fi
          
          echo "=== Starting frontend ==="
          pm2 start npm --name frontend -- run start --cwd $APP_DIR/frontend
          
          echo "=== Waiting for frontend ==="
          sleep 5
          
          echo "=== Testing frontend ==="
          if curl -s http://localhost:3000 > /dev/null; then
            echo "✅ Frontend is responding!"
          else
            echo "❌ Frontend not responding, checking logs..."
            pm2 logs frontend --lines 10
          fi
          
          echo "=== Final PM2 status ==="
          pm2 status
          pm2 save
          
          echo "=== Testing API endpoints ==="
          echo "Backend health check:"
          curl -i http://localhost:3001/api/auth/session 2>/dev/null || echo "API not responding"
          
          echo "=== Reloading Nginx ==="
          sudo systemctl reload nginx
          
          echo "=== Fix completed! ===" 