name: Update Nginx Config

on:
  workflow_dispatch:

jobs:
  update-nginx:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update Nginx Configuration
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "=== Updating Nginx Configuration ==="
          
          # Copy the nginx config from the repo
          cd /home/ec2-user/formatic-unified
          
          # Backup current nginx config
          sudo cp /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.backup || echo "No existing config to backup"
          
          # Copy our nginx config
          sudo cp nginx-datizmo.conf /etc/nginx/conf.d/datizmo.conf
          
          # Remove default config if it conflicts
          sudo rm -f /etc/nginx/conf.d/default.conf
          
          echo "=== Testing Nginx configuration ==="
          sudo nginx -t
          
          if [ $? -eq 0 ]; then
            echo "✅ Nginx config is valid"
            echo "=== Restarting Nginx ==="
            sudo systemctl restart nginx
            sudo systemctl status nginx
            echo "✅ Nginx updated and restarted successfully"
          else
            echo "❌ Nginx config has errors - restoring backup"
            sudo cp /etc/nginx/conf.d/default.conf.backup /etc/nginx/conf.d/default.conf
            sudo rm -f /etc/nginx/conf.d/datizmo.conf
            exit 1
          fi
          
          echo "=== Checking SSL certificate paths ==="
          if [ -f "/etc/ssl/certs/datizmo.com.crt" ] && [ -f "/etc/ssl/private/datizmo.com.key" ]; then
            echo "✅ SSL certificates found"
          else
            echo "⚠️  SSL certificates not found at expected paths"
            echo "Available certificates:"
            sudo find /etc/ssl/ -name "*datizmo*" -o -name "*cert*" | head -10
          fi 