name: Renew SSL Certificates

on:
  workflow_dispatch:

jobs:
  renew-ssl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Renew SSL Certificates
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "=== Checking existing certificates ==="
          sudo ls -la /etc/letsencrypt/live/ || echo "No existing certificates"
          
          echo "=== Checking certbot installation ==="
          which certbot || echo "Certbot not found"
          
          echo "=== Renewing certificates ==="
          sudo certbot renew --quiet --post-hook 'systemctl reload nginx' || echo "Certificate renewal failed"
          
          echo "=== Checking certificate status ==="
          sudo certbot certificates || echo "No certificates found"
          
          echo "=== Testing HTTPS ==="
          curl -I https://datizmo.com || echo "HTTPS test failed" 