name: Restart Services

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    
    steps:
    - name: Restart PM2 Services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "=== Restarting Services ==="
          
          # Source NVM
          export NVM_DIR="/home/ec2-user/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          
          echo "Current PM2 status:"
          pm2 status
          
          echo "=== Restarting services ==="
          pm2 restart all || pm2 start /home/ec2-user/formatic-unified/ecosystem.config.js --env production
          
          echo "Waiting for services to stabilize..."
          sleep 10
          
          echo "=== Final PM2 status ==="
          pm2 status
          
          echo "=== Testing services ==="
          echo "Backend test:"
          curl -s http://localhost:3001/api/auth/session || echo "Backend not responding"
          
          echo "Frontend test:"
          curl -s -I http://localhost:3000 | head -1 || echo "Frontend not responding"
          
          echo "=== External test ==="
          curl -s -I http://datizmo.com | head -1 || echo "External access not working" 