name: Test Deploy

on:
  workflow_dispatch:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Quick Test and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e
          
          echo "🚀 Quick deployment test started"
          
          # Navigate to app directory
          cd /home/ec2-user/formatic-unified
          
          # Update repository
          echo "=== Updating repository ==="
          git fetch origin main
          git reset --hard origin/main
          
          # Setup Node.js environment
          export NVM_DIR="/home/ec2-user/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          
          # Quick backend update
          echo "=== Quick backend update ==="
          cd backend
          npm ci --silent
          npx prisma generate
          npm run build
          
          # Quick frontend update  
          echo "=== Quick frontend update ==="
          cd ../frontend
          npm ci --silent
          npx prisma generate
          
          # Create production environment
          cat > .env.production << EOF
          NODE_ENV=production
          NEXT_PUBLIC_API_URL=http://127.0.0.1:3001
          BACKEND_URL=http://127.0.0.1:3001
          NEXTAUTH_URL=${{ secrets.FRONTEND_URL || 'https://www.datizmo.com' }}
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET || 'fallback-secret' }}
          NEXT_PUBLIC_S3_PUBLIC_URL=https://formatic-uploads-dev.s3.amazonaws.com
          NEXT_PUBLIC_AWS_REGION=eu-west-2
          NEXT_PUBLIC_S3_BUCKET_NAME=formatic-uploads-dev
          EOF
          
          npm run build
          
          # Install PM2 if needed
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi
          
          # Restart applications
          echo "=== Restarting applications ==="
          pm2 stop all || echo "No processes to stop"
          
          # Start backend
          cd ../backend
          pm2 start dist/main.js --name "formatic-app" --cwd /home/ec2-user/formatic-unified/backend || pm2 start dist/src/main.js --name "formatic-app" --cwd /home/ec2-user/formatic-unified/backend
          
          # Start frontend
          cd ../frontend
          pm2 start npm --name "formatic-frontend" -- start
          
          # Save PM2 config
          pm2 save
          
          echo "✅ Quick deployment completed"
          pm2 status 